language: python
python:
  - "3.8"

before_script:
  - cd app
  - python --version
  - pip install -U pip
  - pip install Django==2.1.3
  - pip install djangorestframework==3.9.0
  - pip install flake8==3.6.0

script:
  python manage.py test